apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  replicas: {{ .Values.replicacount.postgres }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.images.postgres }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.user }}
          ports: 
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
         - name: db-data
           persistentVolumeClaim:
                claimName: pvc-postgres
