apiVersion: v1
kind: PersistenVolumeClaim
metadata:
  name: pvc-postgres
  namespace: {{ .Values.namespace }}
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.persistence.postgresSize }}