apiVersion: v1
kind: PersistenVolumeClaim
metadata:
  name: pvc-postgres
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: null