apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  type: {{ .Values.service.postgres.type }}
  ports:
    - name: db
      port: 5432
      targetPort: 5432
  selector:
    app: db
