apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.redis.type }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
