apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
     - ReadWriteOnce
  resources:
     requests:
        storage: {{ .Values.persistence.redisSize }}
