apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: {{ .Values.namespace }}
  labels:
    app: result
spec:
  type: {{ .Values.service.result.type }}
  ports:
    - name: http
      port: 8081
      targetPort: 80
      {{- if eq .Values.service.result.type "NodePort" }}
      nodePort: {{ .Values.service.result.nodePort }}
      {{- end }}
  selector:
    app: result
