apiVersion: apps/v1
kind: Deployment
metadata:
 name: worker
 namespace: {{ .Values.namespace }}
 labels:
  app: worker
spec:
  replicas: {{ .Values.replicacount.worker }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
     labels:
        app: worker
    spec:
      containers:
         - name: worker
           image: {{ .Values.images.worker }}
