namespace: votingapp-lab

images:
  vote: dockersamples/examplevotingapp_vote
  result: dockersamples/examplevotingapp_result
  worker: dockersamples/examplevotingapp_worker
  redis: redis:alpine
  postgres: postgres:15-alpine

replicacount:
  vote: 3
  result: 2
  redis: 1
  postgres: 1
  worker: 1

postgres:
  user: postgres
  password: postgres

service:
  vote:
    type: NodePort
    nodePort: 30002
  result:
    type: NodePort
    nodePort: 31001
  redis:
    type: ClusterIP
  postgres:
    type: ClusterIP

ingress:
  enabled: true
  className: nginx
  voteHost: votelab.itbrasil.net
  resultHost: resultlab.itbrasil.net

persistence:
  postgresSize: 10Gi
  redisSize: 5Gi

resources:
  vote:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 128Mi
readinessProbe:
  enabled: true
  type: exec
  command: ["curl", "-f", "http://localhost:80"]
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  enabled: true
  type: exec
  command: ["curl", "-f", "http://localhost:80"]
  initialDelaySeconds: 10
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 3


