name: Deploy VotingApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar Helm (se necessário)
      run: |
        if ! command -v helm >/dev/null; then
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        fi

    - name: Fazer deploy com Helm
      id: deploy
      run: |
       set -e
       helm upgrade --install votingapp /root/votingapp/helm \
       --wait \
       --timeout 120s

     - name: Fazer rollback se falhar
      if: failure()
      run: |
        echo "Deploy falhou, fazendo o rollback"
        REV=$(helm history votingapp -o json | jq '.[-2].revision')
        helm rollback votingapp $REV
  
